# Используем официальный Go-образ для сборки
FROM golang:1.24.5-alpine AS builder

WORKDIR /app

# Копируем go.mod и go.sum и качаем зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем весь проект
COPY . .

# Собираем бинарник в режиме релиза
RUN go build -o task-controller ./cmd/main.go

# Второй этап — минимальный образ с бинарником
FROM alpine:3.18

# Копируем бинарник из builder
COPY --from=builder /app/task-controller /usr/local/bin/task-controller

# Рабочая папка
WORKDIR /app

# Копируем .env файл (позже смонтируем при запуске)
COPY .env ./

# Запускаем приложение
CMD ["task-controller"]
